
package vista;

import java.awt.Color;

/**
 *
 * @author User
 */
public class Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form Proveedor
     */
    public Proveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        razonSocial = new javax.swing.JTextField();
        rutProveedor = new javax.swing.JTextField();
        nombreContactoproveedor = new javax.swing.JTextField();
        celularProveedor = new javax.swing.JTextField();
        correoProveedor = new javax.swing.JTextField();
        direccionProveedor = new javax.swing.JTextField();
        agregarProveedor = new javax.swing.JButton();
        guardarProveedor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        menuProveedor = new javax.swing.JMenu();
        menuFacturas = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DreamGifts");

        razonSocial.setForeground(new java.awt.Color(102, 102, 102));
        razonSocial.setText("Razon Social");
        razonSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                razonSocialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                razonSocialFocusLost(evt);
            }
        });

        rutProveedor.setForeground(new java.awt.Color(102, 102, 102));
        rutProveedor.setText("Rut Proveedor");
        rutProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rutProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rutProveedorFocusLost(evt);
            }
        });
        rutProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutProveedorActionPerformed(evt);
            }
        });

        nombreContactoproveedor.setForeground(new java.awt.Color(102, 102, 102));
        nombreContactoproveedor.setText("Nombre Contacto");
        nombreContactoproveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreContactoproveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreContactoproveedorFocusLost(evt);
            }
        });

        celularProveedor.setForeground(new java.awt.Color(102, 102, 102));
        celularProveedor.setText("Celular");
        celularProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                celularProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                celularProveedorFocusLost(evt);
            }
        });

        correoProveedor.setForeground(new java.awt.Color(102, 102, 102));
        correoProveedor.setText("Correo");
        correoProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoProveedorFocusLost(evt);
            }
        });

        direccionProveedor.setForeground(new java.awt.Color(102, 102, 102));
        direccionProveedor.setText("Dirección");
        direccionProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionProveedorFocusLost(evt);
            }
        });
        direccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionProveedorActionPerformed(evt);
            }
        });

        agregarProveedor.setText("Agregar");

        guardarProveedor.setText("Guardar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Razón Social", "Rut Proveedor", "Nombre contacto", "Dirección ", "Celular", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(direccionProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celularProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(correoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(razonSocial)
                                .addGap(18, 18, 18)
                                .addComponent(rutProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nombreContactoproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarProveedor)
                            .addComponent(guardarProveedor))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rutProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarProveedor)
                    .addComponent(nombreContactoproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarProveedor))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );

        jMenu1.setText("Ventas");

        jMenu2.setText("Cliente");
        jMenu1.add(jMenu2);

        jMenu3.setText("Articulos");
        jMenu1.add(jMenu3);

        jMenu4.setText("Packs");
        jMenu1.add(jMenu4);

        jMenu5.setText("Bancos");
        jMenu1.add(jMenu5);

        jMenu6.setText("Despacho");
        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Compras");

        menuProveedor.setText("Proveedor");
        jMenu7.add(menuProveedor);

        menuFacturas.setText("Facturas");
        jMenu7.add(menuFacturas);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Informes");

        jMenu11.setText("Listado Inventario");
        jMenu8.add(jMenu11);

        jMenu12.setText("Vencimiento Articulo");
        jMenu8.add(jMenu12);

        jMenu13.setText("Distribución Packs");
        jMenu8.add(jMenu13);

        jMenu14.setText("Informe Ventas Periodo");
        jMenu8.add(jMenu14);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Admin");

        jMenu15.setText("Ventas");
        jMenu9.add(jMenu15);

        jMenu16.setText("Compras");
        jMenu9.add(jMenu16);

        jMenu17.setText("Informes");
        jMenu9.add(jMenu17);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void direccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionProveedorActionPerformed

    private void rutProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutProveedorActionPerformed

    private void razonSocialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_razonSocialFocusGained
        // TODO add your handling code here:
        if(razonSocial.getText().equals("Razon Social")){
            razonSocial.setText("");
        }
    }//GEN-LAST:event_razonSocialFocusGained

    private void rutProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutProveedorFocusGained
        // TODO add your handling code here:
        if(rutProveedor.getText().equals("Rut Proveedor")){
            rutProveedor.setText("");
        }
    }//GEN-LAST:event_rutProveedorFocusGained

    private void nombreContactoproveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreContactoproveedorFocusGained
        // TODO add your handling code here:
        if(nombreContactoproveedor.getText().equals("Nombre Contacto")){
            nombreContactoproveedor.setText("");
        }
    }//GEN-LAST:event_nombreContactoproveedorFocusGained

    private void direccionProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionProveedorFocusGained
        // TODO add your handling code here:
        if(direccionProveedor.getText().equals("Dirección")){
            direccionProveedor.setText("");
        }
    }//GEN-LAST:event_direccionProveedorFocusGained

    private void celularProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularProveedorFocusGained
        // TODO add your handling code here:
        if(celularProveedor.getText().equals("Celular")){
            celularProveedor.setText("");
        }
    }//GEN-LAST:event_celularProveedorFocusGained

    private void correoProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoProveedorFocusGained
        // TODO add your handling code here:
        if(correoProveedor.getText().equals("Correo")){
            correoProveedor.setText("");
        }
    }//GEN-LAST:event_correoProveedorFocusGained

    private void razonSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_razonSocialFocusLost
        // TODO add your handling code here:
        if(razonSocial.getText().equals("")){
            razonSocial.setText("Razon Social");
        }
        razonSocial.setForeground(new Color (102,102,102));
    }//GEN-LAST:event_razonSocialFocusLost

    private void rutProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutProveedorFocusLost
        // TODO add your handling code here:
        if(rutProveedor.getText().equals("")){
            rutProveedor.setText("Rut Proveedor");
        }
        rutProveedor.setForeground(new Color (102,102,102));
    }//GEN-LAST:event_rutProveedorFocusLost

    private void nombreContactoproveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreContactoproveedorFocusLost
        // TODO add your handling code here:
        if(nombreContactoproveedor.getText().equals("")){
            nombreContactoproveedor.setText("Nombre Contacto");
        }
        nombreContactoproveedor.setForeground(new Color (102,102,102));
    }//GEN-LAST:event_nombreContactoproveedorFocusLost

    private void direccionProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionProveedorFocusLost
        // TODO add your handling code here:
        if(direccionProveedor.getText().equals("")){
            direccionProveedor.setText("Dirección");
        }
        direccionProveedor.setForeground(new Color (102,102,102));
    }//GEN-LAST:event_direccionProveedorFocusLost

    private void celularProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_celularProveedorFocusLost
        // TODO add your handling code here:
        if(celularProveedor.getText().equals("")){
            celularProveedor.setText("Celular");
        }
        celularProveedor.setForeground(new Color (102,102,102));
    }//GEN-LAST:event_celularProveedorFocusLost

    private void correoProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoProveedorFocusLost
        // TODO add your handling code here:
        if(correoProveedor.getText().equals("")){
            correoProveedor.setText("Correo");
        }
        correoProveedor.setForeground(new Color (102,102,102));
    }//GEN-LAST:event_correoProveedorFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProveedor;
    private javax.swing.JTextField celularProveedor;
    private javax.swing.JTextField correoProveedor;
    private javax.swing.JTextField direccionProveedor;
    private javax.swing.JButton guardarProveedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menuFacturas;
    private javax.swing.JMenu menuProveedor;
    private javax.swing.JTextField nombreContactoproveedor;
    private javax.swing.JTextField razonSocial;
    private javax.swing.JTextField rutProveedor;
    // End of variables declaration//GEN-END:variables
}
